profanity:
- shit
- fuck
- piss
- cunt

profanityWordMatch:
- ass
- poo
- boob
- boobs
- crap

profanityMessage: "Oi %N! Mind your language!"

blockMessage: "I'm sorry %N, I can't let you do that."

censorText: "!@$#"

triggers:
- eleven
- '11'

triggerPhrase: "That's ridiculous, it's not even funny."

commands:
- r
- msg
- whisper
- f chat
- faction chat 